blueprint:
  name: Better Thermostat Sonnoff TRV positioner
  domain: automation
  author: Thomas Dickinson
  description: |-
    Positions Sonnoff TRV valve opening/ closing position based on target temperature

    Version 1.0, 27/10/2024
  source_url: https://raw.githubusercontent.com/t-d-d/ha-blueprints/refs/heads/master/bt-trvb-position.yaml

  input:
    bt:
      name: Better Thermostats
      description: Better Thermostat that gives target temperature and current temperature
      selector:
        entity:
          integration: better_thermostat
          domain: climate

    valve_closing_degree_entity:
      name: Valve closing degree entity
      description: Input entity to set the valve closing degree
      selector:
        target:
          entity:
            domain: number

    valve_opening_degree_entity:
      name: Valve opening degree entity
      description: Input entity to set the valve opening degree
      selector:
        target:
          entity:
            domain: number

    target_temp_valve_degree:
      name: Target temperature valve opening percentage
      description: Degree to which the valve is left open when at the target temperature
      default: 15
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: '%'

    under_temp_valve_degree:
      name: Under temperature valve opening percentage
      description: Degree to which the valve is open when under target temperature
      default: 100
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: '%'

    target_temperature_range:
      name: Target temperature range
      description: Degrees around the target temperature to consider at temperature
      default: 0.4
      selector:
        number:
          min: 0
          max: 2.0
          step: 0.1
          unit_of_measurement: °C

trigger:
  - platform: state
    entity_id: !input bt
  - platform: state
    entity_id: sensor.boiler_radiator_boost_demand
    to: '0'
  - platform: state
    entity_id: sensor.boiler_radiator_boost_demand
    from: '0'

variables:
  bt: !input bt
  valve_closing_degree_entity: !input valve_closing_degree_entity
  valve_opening_degree_entity: !input valve_opening_degree_entity
  target_temp_valve_degree: !input target_temp_valve_degree
  under_temp_valve_degree: !input under_temp_valve_degree
  target_temperature_range: !input target_temperature_range
  isOverTemperature: "{{ state_attr(bt, 'current_temperature') - state_attr(bt, 'temperature') > target_temperature_range / 2 }}"
  isUnderTemperature: "{{ state_attr(bt, 'temperature') - state_attr(bt, 'current_temperature') > target_temperature_range / 2 }}"
  isBoosting: "{{ not is_state('sensor.boiler_radiator_boost_demand', '0') }}"

condition: []

actions:
  - sequence:
    - service: number.set_value
      target: !input valve_closing_degree_entity
      data_template:
        value: >-
          {% if isUnderTemperature %}
            {{ 100 - under_temp_valve_degree }}
          {% elif isOverTemperature or isBoosting %}
            100
          {% else %}
            {{ 100 - target_temp_valve_degree }}
          {% endif %}
    - service: number.set_value
      target: !input valve_opening_degree_entity
      data_template:
        value: >-
          {% if isUnderTemperature %}
            {{ under_temp_valve_degree }}
          {% elif isOverTemperature or isBoosting %}
            0
          {% else %}
            {{ target_temp_valve_degree }}
          {% endif %}